"""books table and relations to authors

Revision ID: 5242568fc46d
Revises: 1e5f41864e8a
Create Date: 2023-03-17 01:39:42.672254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5242568fc46d'
down_revision = '1e5f41864e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookname', sa.String(length=100), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
